/* ==========================================================================
   8-BIT ORCHARD — front-end logic + procedural pixel-apple sprites
   Data comes from apples.json (generated by build.py). No framework.
   ========================================================================== */

'use strict';

/* ---- Pixel sprite ---------------------------------------------------------
   One 16x16 apple silhouette, recoloured per cultivar. B=body, S=stem, L=leaf.
   Body gets diagonal light shading + a dark outline + a glint, so every apple
   reads as a proper little pixel gem no matter its skin colour.
--------------------------------------------------------------------------- */
const SPRITE = [
  "................",
  ".......S..LL....",
  ".......S.LLL....",
  "......SS.LL.....",
  "....BBB..BBB....",
  "...BBBBBBBBBB...",
  "..BBBBBBBBBBBB..",
  "..BBBBBBBBBBBB..",
  "..BBBBBBBBBBBB..",
  "..BBBBBBBBBBBB..",
  "..BBBBBBBBBBBB..",
  "...BBBBBBBBBB...",
  "...BBBBBBBBBB...",
  "....BBBBBBBB....",
  "....BBB..BBB....",
  ".....B....B.....",
];
const GRID = 16;
const GLINT = new Set(["4,6", "5,6", "4,7"]);
// Columns that carry the blush overlay — weighted to the right ("sun") side,
// with gaps so the base colour shows through as vertical striping.
const BLUSH_COLS = new Set([5, 6, 8, 9, 11, 12, 13]);

function hexToRgb(hex) {
  hex = hex.replace("#", "");
  return [parseInt(hex.slice(0, 2), 16), parseInt(hex.slice(2, 4), 16), parseInt(hex.slice(4, 6), 16)];
}
function shade(hex, amt) {
  // amt in [-1, 1]; positive lightens toward white, negative darkens.
  let [r, g, b] = hexToRgb(hex);
  if (amt >= 0) { r += (255 - r) * amt; g += (255 - g) * amt; b += (255 - b) * amt; }
  else { r *= 1 + amt; g *= 1 + amt; b *= 1 + amt; }
  const c = (n) => Math.max(0, Math.min(255, Math.round(n)));
  return `rgb(${c(r)},${c(g)},${c(b)})`;
}

function cellAt(x, y) {
  if (y < 0 || y >= GRID || x < 0 || x >= GRID) return ".";
  return SPRITE[y][x];
}
function isEmpty(x, y) { return cellAt(x, y) === "."; }

function colorFor(x, y, skin, blush) {
  const c = cellAt(x, y);
  if (c === ".") return null;

  const edge = isEmpty(x - 1, y) || isEmpty(x + 1, y) || isEmpty(x, y - 1) || isEmpty(x, y + 1);

  if (c === "S") return edge ? "#43290f" : "#6f4423";          // stem
  if (c === "L") return edge ? "#3f6b22" : "#74b83e";          // leaf

  // body
  if (edge) return shade(skin, -0.55);                          // outline (base hue)
  if (GLINT.has(`${x},${y}`)) return shade(skin, 0.7);          // glint
  const base = blush && BLUSH_COLS.has(x) ? blush : skin;       // striping
  const lv = (x - 2) / 11 + (y - 4) / 11;                       // 0 = upper-left
  if (lv < 0.55) return shade(base, 0.24);                      // highlight
  if (lv > 1.15) return shade(base, -0.3);                      // shadow
  return base;                                                  // base
}

function drawSprite(canvas, skin, px, blush) {
  canvas.width = GRID * px;
  canvas.height = GRID * px;
  const ctx = canvas.getContext("2d");
  ctx.imageSmoothingEnabled = false;
  ctx.clearRect(0, 0, canvas.width, canvas.height);
  for (let y = 0; y < GRID; y++) {
    for (let x = 0; x < GRID; x++) {
      const col = colorFor(x, y, skin, blush);
      if (!col) continue;
      ctx.fillStyle = col;
      ctx.fillRect(x * px, y * px, px, px);
    }
  }
}

/* ---- State + data -------------------------------------------------------- */
const USES = ["eating", "baking", "cider", "sauce", "salad", "storage"];
let APPLES = [];
const state = { query: "", uses: new Set(), sort: "name" };

const $ = (sel) => document.querySelector(sel);
const grid = $("#grid");

async function boot() {
  try {
    const res = await fetch("apples.json");
    const data = await res.json();
    APPLES = data.apples;
  } catch (err) {
    grid.innerHTML = `<p class="empty">Couldn't load apples.json.<br>Run <code>python serve.py</code> and open via http://localhost:8000</p>`;
    return;
  }
  buildUseFilters();
  wireControls();
  render();
}

function buildUseFilters() {
  const box = $("#use-filters");
  USES.forEach((use) => {
    const chip = document.createElement("button");
    chip.className = "chip";
    chip.textContent = use;
    chip.addEventListener("click", () => {
      chip.classList.toggle("active");
      if (state.uses.has(use)) state.uses.delete(use);
      else state.uses.add(use);
      render();
    });
    box.appendChild(chip);
  });
}

function wireControls() {
  $("#search").addEventListener("input", (e) => { state.query = e.target.value.toLowerCase().trim(); render(); });
  $("#sort").addEventListener("change", (e) => { state.sort = e.target.value; render(); });
  $("#modal-close").addEventListener("click", closeModal);
  $("#modal").addEventListener("click", (e) => { if (e.target.id === "modal") closeModal(); });
  document.addEventListener("keydown", (e) => { if (e.key === "Escape") closeModal(); });

  $("#random").addEventListener("click", () => {
    // Pick from whatever is currently visible, so filters still apply.
    const pool = APPLES.filter(matches);
    const list = pool.length ? pool : APPLES;
    openModal(list[Math.floor(Math.random() * list.length)]);
  });

  const toggle = $("#theme-toggle");
  const syncGlyph = () =>
    (toggle.textContent = document.documentElement.getAttribute("data-theme") === "light" ? "☀" : "☾");
  syncGlyph();
  toggle.addEventListener("click", () => {
    const next = document.documentElement.getAttribute("data-theme") === "light" ? "dark" : "light";
    document.documentElement.setAttribute("data-theme", next);
    localStorage.setItem("orchard-theme", next);
    syncGlyph();
  });
}

/* ---- Filtering + sorting ------------------------------------------------- */
function matches(a) {
  for (const u of state.uses) if (!a.best_for.includes(u)) return false;   // AND across chips
  if (!state.query) return true;
  const hay = [
    a.name, a.aka.join(" "), a.origin.country, a.origin.region,
    a.parentage, a.notes, a.flavor_text, a.season,
  ].join(" ").toLowerCase();
  return hay.includes(state.query);
}

function sortApples(list) {
  const s = state.sort;
  const by = {
    name: (a, b) => a.name.localeCompare(b.name),
    sweetness: (a, b) => b.sweetness - a.sweetness || a.name.localeCompare(b.name),
    tartness: (a, b) => b.tartness - a.tartness || a.name.localeCompare(b.name),
    crispness: (a, b) => b.crispness - a.crispness || a.name.localeCompare(b.name),
    year: (a, b) => a.origin.year - b.origin.year || a.name.localeCompare(b.name),
  };
  return [...list].sort(by[s] || by.name);
}

/* ---- Rendering ----------------------------------------------------------- */
function render() {
  const list = sortApples(APPLES.filter(matches));
  $("#count").textContent = `${list.length} / ${APPLES.length} CULTIVARS`;
  grid.innerHTML = "";
  if (!list.length) {
    grid.innerHTML = `<p class="empty">No apples match that. Try fewer filters. 🍂</p>`;
    return;
  }
  list.forEach((a) => grid.appendChild(card(a)));
}

function card(a) {
  const el = document.createElement("div");
  el.className = "card";
  el.tabIndex = 0;

  const canvas = document.createElement("canvas");
  el.appendChild(canvas);

  const name = document.createElement("div");
  name.className = "card-name";
  name.textContent = a.name;
  el.appendChild(name);

  const origin = document.createElement("div");
  origin.className = "card-origin";
  origin.textContent = `${flag(a.origin.country)} ${a.origin.country} · ${a.origin.year}`;
  el.appendChild(origin);

  const tags = document.createElement("div");
  tags.className = "card-tags";
  a.best_for.slice(0, 3).forEach((u) => {
    const t = document.createElement("span");
    t.className = "tag";
    t.textContent = u;
    tags.appendChild(t);
  });
  el.appendChild(tags);

  el.addEventListener("click", () => openModal(a));
  el.addEventListener("keydown", (e) => { if (e.key === "Enter") openModal(a); });

  drawSprite(canvas, a.skin, 7, a.blush);
  return el;
}

function meter(label, value, cls) {
  const row = document.createElement("div");
  row.className = "meter";
  const lab = document.createElement("span");
  lab.className = "meter-label";
  lab.textContent = label;
  row.appendChild(lab);
  const pips = document.createElement("div");
  pips.className = "pips";
  for (let i = 1; i <= 5; i++) {
    const p = document.createElement("span");
    p.className = "pip" + (i <= value ? ` on-${cls}` : "");
    pips.appendChild(p);
  }
  row.appendChild(pips);
  return row;
}

function flag(country) {
  return {
    "USA": "🇺🇸", "Japan": "🇯🇵", "New Zealand": "🇳🇿", "Australia": "🇦🇺",
    "England": "🏴", "Canada": "🇨🇦",
  }[country] || "🍎";
}

/* ---- Modal --------------------------------------------------------------- */
function openModal(a) {
  const body = $("#modal-body");
  body.innerHTML = "";

  const head = document.createElement("div");
  head.className = "modal-head";
  const canvas = document.createElement("canvas");
  head.appendChild(canvas);
  const htext = document.createElement("div");
  htext.innerHTML =
    `<h2 id="modal-name" class="modal-name">${a.name}</h2>` +
    (a.aka.length ? `<div class="modal-aka">aka ${a.aka.join(", ")}</div>` : "");
  head.appendChild(htext);
  body.appendChild(head);

  const flavor = document.createElement("div");
  flavor.className = "flavor";
  flavor.textContent = `“${a.flavor_text}”`;
  body.appendChild(flavor);

  const stats = document.createElement("div");
  stats.className = "stats-block";
  stats.appendChild(meter("SWEET", a.sweetness, "sweet"));
  stats.appendChild(meter("TART", a.tartness, "tart"));
  stats.appendChild(meter("CRISP", a.crispness, "crisp"));
  body.appendChild(stats);

  body.appendChild(field("ORIGIN", `${flag(a.origin.country)} ${a.origin.region}, ${a.origin.country} — ${a.origin.year}`));
  body.appendChild(field("PARENTAGE", a.parentage));

  const seasonRow = document.createElement("div");
  seasonRow.className = "field-row";
  seasonRow.innerHTML = `<span class="field-key">SEASON</span>`;
  const sb = document.createElement("span");
  sb.className = "badge season";
  sb.textContent = a.season;
  seasonRow.appendChild(sb);
  body.appendChild(seasonRow);

  const useRow = document.createElement("div");
  useRow.className = "field-row";
  useRow.innerHTML = `<span class="field-key">BEST FOR</span>`;
  const badges = document.createElement("div");
  badges.className = "badges";
  a.best_for.forEach((u) => {
    const b = document.createElement("span");
    b.className = "badge use";
    b.textContent = u;
    badges.appendChild(b);
  });
  useRow.appendChild(badges);
  body.appendChild(useRow);

  const notes = document.createElement("div");
  notes.className = "notes";
  notes.textContent = a.notes;
  body.appendChild(notes);

  drawSprite(canvas, a.skin, 8, a.blush);
  $("#modal").classList.remove("hidden");
}

function field(key, val) {
  const row = document.createElement("div");
  row.className = "field-row";
  row.innerHTML = `<span class="field-key">${key}</span><span class="field-val">${val}</span>`;
  return row;
}

function closeModal() { $("#modal").classList.add("hidden"); }

boot();
