/* ==========================================================================
   8-BIT ORCHARD — front-end logic + procedural pixel-apple sprites
   Data comes from apples.json (generated by build.py). No framework.
   ========================================================================== */

'use strict';

/* ---- Pixel sprite ---------------------------------------------------------
   One 16x16 apple silhouette, recoloured per cultivar. B=body, S=stem, L=leaf.
   Body gets diagonal light shading + a dark outline + a glint, so every apple
   reads as a proper little pixel gem no matter its skin colour.
--------------------------------------------------------------------------- */
const SPRITE = [
  "................",
  ".......S..LL....",
  ".......S.LLL....",
  "......SS.LL.....",
  "....BBB..BBB....",
  "...BBBBBBBBBB...",
  "..BBBBBBBBBBBB..",
  "..BBBBBBBBBBBB..",
  "..BBBBBBBBBBBB..",
  "..BBBBBBBBBBBB..",
  "..BBBBBBBBBBBB..",
  "...BBBBBBBBBB...",
  "...BBBBBBBBBB...",
  "....BBBBBBBB....",
  "....BBB..BBB....",
  ".....B....B.....",
];
const GRID = 16;
const GLINT = new Set(["4,6", "5,6", "4,7"]);
// Columns that carry the blush overlay — weighted to the right ("sun") side,
// with gaps so the base colour shows through as vertical striping.
const BLUSH_COLS = new Set([5, 6, 8, 9, 11, 12, 13]);

function hexToRgb(hex) {
  hex = hex.replace("#", "");
  return [parseInt(hex.slice(0, 2), 16), parseInt(hex.slice(2, 4), 16), parseInt(hex.slice(4, 6), 16)];
}
function shade(hex, amt) {
  // amt in [-1, 1]; positive lightens toward white, negative darkens.
  let [r, g, b] = hexToRgb(hex);
  if (amt >= 0) { r += (255 - r) * amt; g += (255 - g) * amt; b += (255 - b) * amt; }
  else { r *= 1 + amt; g *= 1 + amt; b *= 1 + amt; }
  const c = (n) => Math.max(0, Math.min(255, Math.round(n)));
  return `rgb(${c(r)},${c(g)},${c(b)})`;
}

function cellAt(x, y) {
  if (y < 0 || y >= GRID || x < 0 || x >= GRID) return ".";
  return SPRITE[y][x];
}
function isEmpty(x, y) { return cellAt(x, y) === "."; }

function colorFor(x, y, skin, blush) {
  const c = cellAt(x, y);
  if (c === ".") return null;

  const edge = isEmpty(x - 1, y) || isEmpty(x + 1, y) || isEmpty(x, y - 1) || isEmpty(x, y + 1);

  if (c === "S") return edge ? "#43290f" : "#6f4423";          // stem
  if (c === "L") return edge ? "#3f6b22" : "#74b83e";          // leaf

  // body
  if (edge) return shade(skin, -0.55);                          // outline (base hue)
  if (GLINT.has(`${x},${y}`)) return shade(skin, 0.7);          // glint
  const base = blush && BLUSH_COLS.has(x) ? blush : skin;       // striping
  const lv = (x - 2) / 11 + (y - 4) / 11;                       // 0 = upper-left
  if (lv < 0.55) return shade(base, 0.24);                      // highlight
  if (lv > 1.15) return shade(base, -0.3);                      // shadow
  return base;                                                  // base
}

function drawSprite(canvas, skin, px, blush) {
  canvas.width = GRID * px;
  canvas.height = GRID * px;
  const ctx = canvas.getContext("2d");
  ctx.imageSmoothingEnabled = false;
  ctx.clearRect(0, 0, canvas.width, canvas.height);
  for (let y = 0; y < GRID; y++) {
    for (let x = 0; x < GRID; x++) {
      const col = colorFor(x, y, skin, blush);
      if (!col) continue;
      ctx.fillStyle = col;
      ctx.fillRect(x * px, y * px, px, px);
    }
  }
}

/* ---- Pixel flags ----------------------------------------------------------
   Emoji flags don't render on Windows, so we draw tiny 12x8 pixel flags on a
   canvas instead — cross-platform and on-theme. w=white r=red b=blue.
--------------------------------------------------------------------------- */
const FLAG_PAL = { w: "#f5f5f5", r: "#d8352b", b: "#1f3f93", y: "#f4d02a", k: "#1c1c22", g: "#2f9e44" };
const FLAGS = {
  "USA": [
    "bbbbbrrrrrrr", "bwbwbwwwwwww", "bbbbbrrrrrrr", "bwbwbwwwwwww",
    "rrrrrrrrrrrr", "wwwwwwwwwwww", "rrrrrrrrrrrr", "wwwwwwwwwwww",
  ],
  "Japan": [
    "wwwwwwwwwwww", "wwwwwwwwwwww", "wwwwrrrrwwww", "wwwrrrrrrwww",
    "wwwrrrrrrwww", "wwwwrrrrwwww", "wwwwwwwwwwww", "wwwwwwwwwwww",
  ],
  "England": [
    "wwwwwrrwwwww", "wwwwwrrwwwww", "wwwwwrrwwwww", "rrrrrrrrrrrr",
    "rrrrrrrrrrrr", "wwwwwrrwwwww", "wwwwwrrwwwww", "wwwwwrrwwwww",
  ],
  "Canada": [
    "rrrwwwwwwrrr", "rrrwwwwwwrrr", "rrrwwrrwwrrr", "rrrwrrrrwrrr",
    "rrrwwrrwwrrr", "rrrwwwrwwrrr", "rrrwwwwwwrrr", "rrrwwwwwwrrr",
  ],
  "New Zealand": [
    "wbrbwbbbbbbb", "bwrwbbbbbbbb", "rrrrrbbbbrbb", "bwrwbbbbbbbb",
    "bbbbbbbbrbrb", "bbbbbbbbbbbb", "bbbbbbbbbrbb", "bbbbbbbbbbbb",
  ],
  "Australia": [
    "wbrbwbbbbbbb", "bwrwbbbbbbbb", "rrrrrbbbbwbb", "bwrwbbbbbbbb",
    "bbbbbbbbwbwb", "bbwbbbbbbbbb", "bbbbbbbbbwbb", "bbbbbbbbbbbb",
  ],
  "France": [
    "bbbbwwwwrrrr", "bbbbwwwwrrrr", "bbbbwwwwrrrr", "bbbbwwwwrrrr",
    "bbbbwwwwrrrr", "bbbbwwwwrrrr", "bbbbwwwwrrrr", "bbbbwwwwrrrr",
  ],
  "Netherlands": [
    "rrrrrrrrrrrr", "rrrrrrrrrrrr", "rrrrrrrrrrrr", "wwwwwwwwwwww",
    "wwwwwwwwwwww", "bbbbbbbbbbbb", "bbbbbbbbbbbb", "bbbbbbbbbbbb",
  ],
  "Denmark": [
    "rrrwwrrrrrrr", "rrrwwrrrrrrr", "rrrwwrrrrrrr", "wwwwwwwwwwww",
    "wwwwwwwwwwww", "rrrwwrrrrrrr", "rrrwwrrrrrrr", "rrrwwrrrrrrr",
  ],
  "Sweden": [
    "bbbyybbbbbbb", "bbbyybbbbbbb", "bbbyybbbbbbb", "yyyyyyyyyyyy",
    "yyyyyyyyyyyy", "bbbyybbbbbbb", "bbbyybbbbbbb", "bbbyybbbbbbb",
  ],
  "Belgium": [
    "kkkkyyyyrrrr", "kkkkyyyyrrrr", "kkkkyyyyrrrr", "kkkkyyyyrrrr",
    "kkkkyyyyrrrr", "kkkkyyyyrrrr", "kkkkyyyyrrrr", "kkkkyyyyrrrr",
  ],
  "Scotland": [
    "wwbbbbbbbbww", "bwwbbbbbbwwb", "bbwwbbbbwwbb", "bbbwwbbwwbbb",
    "bbbwwbbwwbbb", "bbwwbbbbwwbb", "bwwbbbbbbwwb", "wwbbbbbbbbww",
  ],
  "Germany": [
    "kkkkkkkkkkkk", "kkkkkkkkkkkk", "kkkkkkkkkkkk", "rrrrrrrrrrrr",
    "rrrrrrrrrrrr", "yyyyyyyyyyyy", "yyyyyyyyyyyy", "yyyyyyyyyyyy",
  ],
  "Czech Republic": [
    "bbwwwwwwwwww", "bbbwwwwwwwww", "bbbbwwwwwwww", "bbbbbwwwwwww",
    "bbbbbrrrrrrr", "bbbbrrrrrrrr", "bbbrrrrrrrrr", "bbrrrrrrrrrr",
  ],
  "Italy": [
    "ggggwwwwrrrr", "ggggwwwwrrrr", "ggggwwwwrrrr", "ggggwwwwrrrr",
    "ggggwwwwrrrr", "ggggwwwwrrrr", "ggggwwwwrrrr", "ggggwwwwrrrr",
  ],
};

function flagEl(country) {
  const rows = FLAGS[country];
  if (!rows) return null;
  const px = 2;
  const canvas = document.createElement("canvas");
  canvas.className = "flag";
  canvas.width = rows[0].length * px;
  canvas.height = rows.length * px;
  const ctx = canvas.getContext("2d");
  ctx.imageSmoothingEnabled = false;
  rows.forEach((row, y) => {
    for (let x = 0; x < row.length; x++) {
      ctx.fillStyle = FLAG_PAL[row[x]];
      ctx.fillRect(x * px, y * px, px, px);
    }
  });
  return canvas;
}

/* ---- State + data -------------------------------------------------------- */
let APPLES = [];
const faves = new Set(JSON.parse(localStorage.getItem("orchard-faves") || "[]"));
const state = {
  query: "",
  sort: "name",
  season: "all",
  favesOnly: false,
  compare: [],   // up to 2 apple ids selected for side-by-side
  muted: localStorage.getItem("orchard-muted") === "1",
};

/* ---- Sound: tiny WebAudio chiptune blips ---------------------------------- */
let audioCtx = null;
function blip(freq = 660, dur = 0.08, type = "square") {
  if (state.muted) return;
  try {
    audioCtx = audioCtx || new (window.AudioContext || window.webkitAudioContext)();
    const osc = audioCtx.createOscillator();
    const gain = audioCtx.createGain();
    osc.type = type;
    osc.frequency.value = freq;
    gain.gain.setValueAtTime(0.06, audioCtx.currentTime);
    gain.gain.exponentialRampToValueAtTime(0.0001, audioCtx.currentTime + dur);
    osc.connect(gain).connect(audioCtx.destination);
    osc.start();
    osc.stop(audioCtx.currentTime + dur);
  } catch (e) { /* audio unavailable — no-op */ }
}

/* ---- Favourites ---------------------------------------------------------- */
function isFave(id) { return faves.has(id); }
function toggleFave(id) {
  if (faves.has(id)) { faves.delete(id); blip(392, 0.09); }
  else { faves.add(id); blip(784, 0.09); }
  localStorage.setItem("orchard-faves", JSON.stringify([...faves]));
  render();
}

/* ---- Compare (pick two, view side by side) ------------------------------- */
function toggleCompare(id) {
  const i = state.compare.indexOf(id);
  if (i >= 0) { state.compare.splice(i, 1); blip(440, 0.07); }
  else {
    if (state.compare.length >= 2) state.compare.shift();  // drop the oldest pick
    state.compare.push(id);
    blip(660, 0.07);
  }
  render();
}

function renderCompareTray() {
  const tray = $("#compare-tray");
  const picks = state.compare.map(byId).filter(Boolean);
  tray.innerHTML = "";
  if (!picks.length) { tray.classList.add("hidden"); return; }
  tray.classList.remove("hidden");

  const label = document.createElement("span");
  label.className = "tray-label";
  label.textContent = "COMPARE";
  tray.appendChild(label);

  picks.forEach((a) => {
    const chip = document.createElement("button");
    chip.className = "tray-chip";
    const c = document.createElement("canvas");
    c.className = "tray-sprite";
    chip.appendChild(c);
    chip.appendChild(document.createTextNode(`${a.name} ✕`));
    chip.title = "Remove from compare";
    chip.addEventListener("click", () => toggleCompare(a.id));
    tray.appendChild(chip);
    drawSprite(c, a.skin, 3, a.blush);
  });

  if (picks.length === 2) {
    const go = document.createElement("button");
    go.className = "tray-go";
    go.textContent = "VS →";
    go.addEventListener("click", openCompare);
    tray.appendChild(go);
  } else {
    const hint = document.createElement("span");
    hint.className = "tray-hint";
    hint.textContent = "pick one more";
    tray.appendChild(hint);
  }

  const clear = document.createElement("button");
  clear.className = "tray-clear";
  clear.textContent = "CLEAR";
  clear.addEventListener("click", () => { state.compare = []; render(); });
  tray.appendChild(clear);
}

function comparePips(value, cls, align) {
  const pips = document.createElement("div");
  pips.className = `pips compare-pips ${align}`;
  for (let i = 1; i <= 5; i++) {
    const p = document.createElement("span");
    p.className = "pip" + (i <= value ? ` on-${cls}` : "");
    pips.appendChild(p);
  }
  return pips;
}

function openCompare() {
  const [a, b] = state.compare.map(byId);
  if (!a || !b) return;
  const body = $("#modal-body");
  body.innerHTML = "";

  const wrap = document.createElement("div");
  wrap.className = "compare";

  const heads = document.createElement("div");
  heads.className = "compare-heads";
  [a, b].forEach((ap) => {
    const h = document.createElement("div");
    h.className = "compare-head";
    const c = document.createElement("canvas");
    c.className = "compare-sprite";
    h.appendChild(c);
    const nm = document.createElement("div");
    nm.className = "compare-name";
    nm.textContent = ap.name;
    h.appendChild(nm);
    const og = document.createElement("div");
    og.className = "compare-origin";
    const fe = flagEl(ap.origin.country);
    if (fe) og.appendChild(fe);
    og.appendChild(document.createTextNode(` ${ap.origin.country} · ${ap.origin.year}`));
    h.appendChild(og);
    const se = document.createElement("div");
    se.className = "compare-season";
    se.textContent = ap.season;
    h.appendChild(se);
    heads.appendChild(h);
    drawSprite(c, ap.skin, 6, ap.blush);
  });
  wrap.appendChild(heads);

  const stats = document.createElement("div");
  stats.className = "compare-stats";
  [["SWEET", "sweetness", "sweet"], ["TART", "tartness", "tart"], ["CRISP", "crispness", "crisp"]]
    .forEach(([label, key, cls]) => {
      const row = document.createElement("div");
      row.className = "compare-row";
      row.appendChild(comparePips(a[key], cls, "right"));
      const lab = document.createElement("span");
      lab.className = "compare-stat-label";
      lab.textContent = label;
      row.appendChild(lab);
      row.appendChild(comparePips(b[key], cls, "left"));
      stats.appendChild(row);
    });
  wrap.appendChild(stats);

  body.appendChild(wrap);
  $("#modal").classList.remove("hidden");
  blip(523, 0.1);
}

const $ = (sel) => document.querySelector(sel);
const grid = $("#grid");

async function boot() {
  try {
    const res = await fetch("apples.json");
    const data = await res.json();
    APPLES = data.apples;
  } catch (err) {
    grid.innerHTML = `<p class="empty">Couldn't load apples.json.<br>Run <code>python serve.py</code> and open via http://localhost:8000</p>`;
    return;
  }
  wireControls();
  render();
  openFromHash();
  window.addEventListener("hashchange", openFromHash);
}

function wireControls() {
  $("#search").addEventListener("input", (e) => { state.query = e.target.value.toLowerCase().trim(); render(); });
  $("#sort").addEventListener("change", (e) => { state.sort = e.target.value; render(); });
  $("#season").addEventListener("change", (e) => { state.season = e.target.value; render(); });

  const favesBtn = $("#faves-toggle");
  favesBtn.addEventListener("click", () => {
    state.favesOnly = !state.favesOnly;
    favesBtn.classList.toggle("active", state.favesOnly);
    blip(state.favesOnly ? 587 : 494, 0.07);
    render();
  });

  const soundBtn = $("#sound-toggle");
  const syncSound = () => { soundBtn.textContent = state.muted ? "🔇" : "🔊"; };
  syncSound();
  soundBtn.addEventListener("click", () => {
    state.muted = !state.muted;
    localStorage.setItem("orchard-muted", state.muted ? "1" : "0");
    syncSound();
    blip(660, 0.07); // audible confirmation when un-muting
  });

  const toTop = $("#to-top");
  toTop.addEventListener("click", () => window.scrollTo({ top: 0, behavior: "smooth" }));
  const syncToTop = () => toTop.classList.toggle("show", window.scrollY > 400);
  window.addEventListener("scroll", syncToTop, { passive: true });
  syncToTop();
  $("#modal-close").addEventListener("click", closeModal);
  $("#modal").addEventListener("click", (e) => { if (e.target.id === "modal") closeModal(); });
  document.addEventListener("keydown", (e) => { if (e.key === "Escape") closeModal(); });

  $("#random").addEventListener("click", () => {
    // Pick from whatever is currently visible, so filters still apply.
    const pool = APPLES.filter(matches);
    const list = pool.length ? pool : APPLES;
    openModal(list[Math.floor(Math.random() * list.length)]);
  });

  const toggle = $("#theme-toggle");
  const syncGlyph = () =>
    (toggle.textContent = document.documentElement.getAttribute("data-theme") === "light" ? "☀" : "☾");
  syncGlyph();
  toggle.addEventListener("click", () => {
    const next = document.documentElement.getAttribute("data-theme") === "light" ? "dark" : "light";
    document.documentElement.setAttribute("data-theme", next);
    localStorage.setItem("orchard-theme", next);
    syncGlyph();
  });
}

/* ---- Filtering + sorting ------------------------------------------------- */
function matches(a) {
  if (state.favesOnly && !faves.has(a.id)) return false;
  if (state.season !== "all" && a.season !== state.season) return false;
  if (!state.query) return true;
  const hay = [
    a.name, a.aka.join(" "), a.origin.country, a.origin.region,
    a.parentage, a.notes, a.flavor_text, a.season,
  ].join(" ").toLowerCase();
  return hay.includes(state.query);
}

function sortApples(list) {
  const s = state.sort;
  const by = {
    name: (a, b) => a.name.localeCompare(b.name),
    sweetness: (a, b) => b.sweetness - a.sweetness || a.name.localeCompare(b.name),
    tartness: (a, b) => b.tartness - a.tartness || a.name.localeCompare(b.name),
    crispness: (a, b) => b.crispness - a.crispness || a.name.localeCompare(b.name),
    year: (a, b) => a.origin.year - b.origin.year || a.name.localeCompare(b.name),
  };
  return [...list].sort(by[s] || by.name);
}

/* ---- Rendering ----------------------------------------------------------- */
function render() {
  const list = sortApples(APPLES.filter(matches));
  $("#count").textContent = `${list.length} / ${APPLES.length} CULTIVARS`;
  renderCompareTray();
  grid.innerHTML = "";
  if (!list.length) {
    grid.innerHTML = `<p class="empty">No apples match that. Try fewer filters. 🍂</p>`;
    return;
  }
  list.forEach((a) => grid.appendChild(card(a)));
}

function card(a) {
  const el = document.createElement("div");
  el.className = "card";
  el.tabIndex = 0;

  const star = document.createElement("button");
  star.className = "star" + (isFave(a.id) ? " on" : "");
  star.textContent = isFave(a.id) ? "★" : "☆";
  star.title = "Favourite";
  star.setAttribute("aria-label", "Toggle favourite");
  star.addEventListener("click", (e) => { e.stopPropagation(); toggleFave(a.id); });
  el.appendChild(star);

  const cmp = document.createElement("button");
  cmp.className = "cmp" + (state.compare.includes(a.id) ? " on" : "");
  cmp.textContent = "⚖";
  cmp.title = "Add to compare";
  cmp.setAttribute("aria-label", "Add to compare");
  cmp.addEventListener("click", (e) => { e.stopPropagation(); toggleCompare(a.id); });
  el.appendChild(cmp);

  const canvas = document.createElement("canvas");
  canvas.className = "sprite";
  el.appendChild(canvas);

  const name = document.createElement("div");
  name.className = "card-name";
  name.textContent = a.name;
  el.appendChild(name);

  const origin = document.createElement("div");
  origin.className = "card-origin";
  const fe = flagEl(a.origin.country);
  if (fe) origin.appendChild(fe);
  origin.appendChild(document.createTextNode(` ${a.origin.country} · ${a.origin.year}`));
  el.appendChild(origin);

  const tags = document.createElement("div");
  tags.className = "card-tags";
  a.best_for.slice(0, 3).forEach((u) => {
    const t = document.createElement("span");
    t.className = "tag";
    t.textContent = u;
    tags.appendChild(t);
  });
  el.appendChild(tags);

  el.addEventListener("click", () => openModal(a));
  el.addEventListener("keydown", (e) => { if (e.key === "Enter") openModal(a); });
  // (blip on open is handled in openModal so keyboard + random button share it)

  drawSprite(canvas, a.skin, 7, a.blush);
  return el;
}

function meter(label, value, cls) {
  const row = document.createElement("div");
  row.className = "meter";
  const lab = document.createElement("span");
  lab.className = "meter-label";
  lab.textContent = label;
  row.appendChild(lab);
  const pips = document.createElement("div");
  pips.className = "pips";
  for (let i = 1; i <= 5; i++) {
    const p = document.createElement("span");
    p.className = "pip" + (i <= value ? ` on-${cls}` : "");
    pips.appendChild(p);
  }
  row.appendChild(pips);
  return row;
}

/* ---- Modal --------------------------------------------------------------- */
function openModal(a) {
  const body = $("#modal-body");
  body.innerHTML = "";

  const head = document.createElement("div");
  head.className = "modal-head";
  const canvas = document.createElement("canvas");
  head.appendChild(canvas);
  const htext = document.createElement("div");
  htext.innerHTML =
    `<h2 id="modal-name" class="modal-name">${a.name}</h2>` +
    (a.aka.length ? `<div class="modal-aka">aka ${a.aka.join(", ")}</div>` : "");

  const actions = document.createElement("div");
  actions.className = "modal-actions";

  const star = document.createElement("button");
  star.className = "modal-star" + (isFave(a.id) ? " on" : "");
  star.textContent = isFave(a.id) ? "★ FAVOURITE" : "☆ FAVOURITE";
  star.addEventListener("click", () => {
    toggleFave(a.id);
    const on = isFave(a.id);
    star.className = "modal-star" + (on ? " on" : "");
    star.textContent = on ? "★ FAVOURITE" : "☆ FAVOURITE";
  });
  actions.appendChild(star);

  const cmpBtn = document.createElement("button");
  const inCmp = () => state.compare.includes(a.id);
  const syncCmp = () => {
    cmpBtn.className = "modal-cmp" + (inCmp() ? " on" : "");
    cmpBtn.textContent = inCmp() ? "⚖ COMPARING" : "⚖ COMPARE";
  };
  syncCmp();
  cmpBtn.addEventListener("click", () => { toggleCompare(a.id); syncCmp(); });
  actions.appendChild(cmpBtn);

  htext.appendChild(actions);
  head.appendChild(htext);
  body.appendChild(head);

  const flavor = document.createElement("div");
  flavor.className = "flavor";
  flavor.textContent = `“${a.flavor_text}”`;
  body.appendChild(flavor);

  const stats = document.createElement("div");
  stats.className = "stats-block";
  stats.appendChild(meter("SWEET", a.sweetness, "sweet"));
  stats.appendChild(meter("TART", a.tartness, "tart"));
  stats.appendChild(meter("CRISP", a.crispness, "crisp"));
  body.appendChild(stats);

  const originRow = document.createElement("div");
  originRow.className = "field-row";
  originRow.innerHTML = `<span class="field-key">ORIGIN</span>`;
  const originVal = document.createElement("span");
  originVal.className = "field-val";
  const mfe = flagEl(a.origin.country);
  if (mfe) originVal.append(mfe, document.createTextNode(" "));
  originVal.append(document.createTextNode(`${a.origin.region}, ${a.origin.country} — ${a.origin.year}`));
  originRow.appendChild(originVal);
  body.appendChild(originRow);

  body.appendChild(field("PARENTAGE", a.parentage));

  const seasonRow = document.createElement("div");
  seasonRow.className = "field-row";
  seasonRow.innerHTML = `<span class="field-key">SEASON</span>`;
  const sb = document.createElement("span");
  sb.className = "badge season";
  sb.textContent = a.season;
  seasonRow.appendChild(sb);
  body.appendChild(seasonRow);

  const useRow = document.createElement("div");
  useRow.className = "field-row";
  useRow.innerHTML = `<span class="field-key">BEST FOR</span>`;
  const badges = document.createElement("div");
  badges.className = "badges";
  a.best_for.forEach((u) => {
    const b = document.createElement("span");
    b.className = "badge use";
    b.textContent = u;
    badges.appendChild(b);
  });
  useRow.appendChild(badges);
  body.appendChild(useRow);

  const notes = document.createElement("div");
  notes.className = "notes";
  notes.textContent = a.notes;
  body.appendChild(notes);

  const wiki = document.createElement("a");
  wiki.className = "wiki-link";
  wiki.href = a.wiki || `https://en.wikipedia.org/w/index.php?search=${encodeURIComponent(a.name + " apple")}`;
  wiki.target = "_blank";
  wiki.rel = "noopener";
  wiki.textContent = "WIKIPEDIA ↗";
  body.appendChild(wiki);

  drawSprite(canvas, a.skin, 8, a.blush);
  $("#modal").classList.remove("hidden");
  setHash(a.id);
  blip(660, 0.09);
}

function field(key, val) {
  const row = document.createElement("div");
  row.className = "field-row";
  row.innerHTML = `<span class="field-key">${key}</span><span class="field-val">${val}</span>`;
  return row;
}

function closeModal() {
  $("#modal").classList.add("hidden");
  setHash(null);
}

/* ---- Shareable links (#slug) --------------------------------------------- */
const byId = (id) => APPLES.find((a) => a.id === id);

function setHash(id) {
  const base = location.pathname + location.search;
  history.replaceState(null, "", id ? `${base}#${id}` : base);
}

function openFromHash() {
  const id = decodeURIComponent(location.hash.slice(1));
  if (!id) {
    if (!$("#modal").classList.contains("hidden")) closeModal();
    return;
  }
  const apple = byId(id);
  if (apple) openModal(apple);
}

boot();
