/* ==========================================================================
   8-BIT ORCHARD — front-end logic + procedural pixel-apple sprites
   Data comes from apples.json (generated by build.py). No framework.
   ========================================================================== */

'use strict';

/* ---- Pixel sprite ---------------------------------------------------------
   One 16x16 apple silhouette, recoloured per cultivar. B=body, S=stem, L=leaf.
   Body gets diagonal light shading + a dark outline + a glint, so every apple
   reads as a proper little pixel gem no matter its skin colour.
--------------------------------------------------------------------------- */
const SPRITE = [
  "................",
  ".......S..LL....",
  ".......S.LLL....",
  "......SS.LL.....",
  "....BBB..BBB....",
  "...BBBBBBBBBB...",
  "..BBBBBBBBBBBB..",
  "..BBBBBBBBBBBB..",
  "..BBBBBBBBBBBB..",
  "..BBBBBBBBBBBB..",
  "..BBBBBBBBBBBB..",
  "...BBBBBBBBBB...",
  "...BBBBBBBBBB...",
  "....BBBBBBBB....",
  "....BBB..BBB....",
  ".....B....B.....",
];
const GRID = 16;
const GLINT = new Set(["4,6", "5,6", "4,7"]);
// Columns that carry the blush overlay — weighted to the right ("sun") side,
// with gaps so the base colour shows through as vertical striping.
const BLUSH_COLS = new Set([5, 6, 8, 9, 11, 12, 13]);

function hexToRgb(hex) {
  hex = hex.replace("#", "");
  return [parseInt(hex.slice(0, 2), 16), parseInt(hex.slice(2, 4), 16), parseInt(hex.slice(4, 6), 16)];
}
function shade(hex, amt) {
  // amt in [-1, 1]; positive lightens toward white, negative darkens.
  let [r, g, b] = hexToRgb(hex);
  if (amt >= 0) { r += (255 - r) * amt; g += (255 - g) * amt; b += (255 - b) * amt; }
  else { r *= 1 + amt; g *= 1 + amt; b *= 1 + amt; }
  const c = (n) => Math.max(0, Math.min(255, Math.round(n)));
  return `rgb(${c(r)},${c(g)},${c(b)})`;
}

function cellAt(x, y) {
  if (y < 0 || y >= GRID || x < 0 || x >= GRID) return ".";
  return SPRITE[y][x];
}
function isEmpty(x, y) { return cellAt(x, y) === "."; }

function colorFor(x, y, skin, blush) {
  const c = cellAt(x, y);
  if (c === ".") return null;

  const edge = isEmpty(x - 1, y) || isEmpty(x + 1, y) || isEmpty(x, y - 1) || isEmpty(x, y + 1);

  if (c === "S") return edge ? "#43290f" : "#6f4423";          // stem
  if (c === "L") return edge ? "#3f6b22" : "#74b83e";          // leaf

  // body
  if (edge) return shade(skin, -0.55);                          // outline (base hue)
  if (GLINT.has(`${x},${y}`)) return shade(skin, 0.7);          // glint
  const base = blush && BLUSH_COLS.has(x) ? blush : skin;       // striping
  const lv = (x - 2) / 11 + (y - 4) / 11;                       // 0 = upper-left
  if (lv < 0.55) return shade(base, 0.24);                      // highlight
  if (lv > 1.15) return shade(base, -0.3);                      // shadow
  return base;                                                  // base
}

function drawSprite(canvas, skin, px, blush) {
  canvas.width = GRID * px;
  canvas.height = GRID * px;
  const ctx = canvas.getContext("2d");
  ctx.imageSmoothingEnabled = false;
  ctx.clearRect(0, 0, canvas.width, canvas.height);
  for (let y = 0; y < GRID; y++) {
    for (let x = 0; x < GRID; x++) {
      const col = colorFor(x, y, skin, blush);
      if (!col) continue;
      ctx.fillStyle = col;
      ctx.fillRect(x * px, y * px, px, px);
    }
  }
}

/* ---- Pixel flags ----------------------------------------------------------
   Emoji flags don't render on Windows, so we draw tiny 12x8 pixel flags on a
   canvas instead — cross-platform and on-theme. w=white r=red b=blue.
--------------------------------------------------------------------------- */
const FLAG_PAL = { w: "#f5f5f5", r: "#d8352b", b: "#1f3f93", y: "#f4d02a" };
const FLAGS = {
  "USA": [
    "bbbbbrrrrrrr", "bwbwbwwwwwww", "bbbbbrrrrrrr", "bwbwbwwwwwww",
    "rrrrrrrrrrrr", "wwwwwwwwwwww", "rrrrrrrrrrrr", "wwwwwwwwwwww",
  ],
  "Japan": [
    "wwwwwwwwwwww", "wwwwwwwwwwww", "wwwwrrrrwwww", "wwwrrrrrrwww",
    "wwwrrrrrrwww", "wwwwrrrrwwww", "wwwwwwwwwwww", "wwwwwwwwwwww",
  ],
  "England": [
    "wwwwwrrwwwww", "wwwwwrrwwwww", "wwwwwrrwwwww", "rrrrrrrrrrrr",
    "rrrrrrrrrrrr", "wwwwwrrwwwww", "wwwwwrrwwwww", "wwwwwrrwwwww",
  ],
  "Canada": [
    "rrrwwwwwwrrr", "rrrwwwwwwrrr", "rrrwwrrwwrrr", "rrrwrrrrwrrr",
    "rrrwwrrwwrrr", "rrrwwwrwwrrr", "rrrwwwwwwrrr", "rrrwwwwwwrrr",
  ],
  "New Zealand": [
    "wbrbwbbbbbbb", "bwrwbbbbbbbb", "rrrrrbbbbrbb", "bwrwbbbbbbbb",
    "bbbbbbbbrbrb", "bbbbbbbbbbbb", "bbbbbbbbbrbb", "bbbbbbbbbbbb",
  ],
  "Australia": [
    "wbrbwbbbbbbb", "bwrwbbbbbbbb", "rrrrrbbbbwbb", "bwrwbbbbbbbb",
    "bbbbbbbbwbwb", "bbwbbbbbbbbb", "bbbbbbbbbwbb", "bbbbbbbbbbbb",
  ],
  "France": [
    "bbbbwwwwrrrr", "bbbbwwwwrrrr", "bbbbwwwwrrrr", "bbbbwwwwrrrr",
    "bbbbwwwwrrrr", "bbbbwwwwrrrr", "bbbbwwwwrrrr", "bbbbwwwwrrrr",
  ],
  "Netherlands": [
    "rrrrrrrrrrrr", "rrrrrrrrrrrr", "rrrrrrrrrrrr", "wwwwwwwwwwww",
    "wwwwwwwwwwww", "bbbbbbbbbbbb", "bbbbbbbbbbbb", "bbbbbbbbbbbb",
  ],
  "Denmark": [
    "rrrwwrrrrrrr", "rrrwwrrrrrrr", "rrrwwrrrrrrr", "wwwwwwwwwwww",
    "wwwwwwwwwwww", "rrrwwrrrrrrr", "rrrwwrrrrrrr", "rrrwwrrrrrrr",
  ],
  "Sweden": [
    "bbbyybbbbbbb", "bbbyybbbbbbb", "bbbyybbbbbbb", "yyyyyyyyyyyy",
    "yyyyyyyyyyyy", "bbbyybbbbbbb", "bbbyybbbbbbb", "bbbyybbbbbbb",
  ],
};

function flagEl(country) {
  const rows = FLAGS[country];
  if (!rows) return null;
  const px = 2;
  const canvas = document.createElement("canvas");
  canvas.className = "flag";
  canvas.width = rows[0].length * px;
  canvas.height = rows.length * px;
  const ctx = canvas.getContext("2d");
  ctx.imageSmoothingEnabled = false;
  rows.forEach((row, y) => {
    for (let x = 0; x < row.length; x++) {
      ctx.fillStyle = FLAG_PAL[row[x]];
      ctx.fillRect(x * px, y * px, px, px);
    }
  });
  return canvas;
}

/* ---- Pixel world map -------------------------------------------------------
   A stylised 64x32 equirectangular map. Land is defined as inclusive column
   spans per row; countries are pinned by grid cell. Drawn once to a canvas;
   clickable markers are HTML overlaid on top by percentage position.
--------------------------------------------------------------------------- */
const MAP_W = 64, MAP_H = 32;
const LAND = [
  [], [[6, 12], [22, 26], [42, 60]], [[3, 15], [21, 27], [30, 62]],
  [[3, 16], [21, 26], [29, 63]], [[2, 18], [22, 25], [29, 63]],
  [[2, 20], [23, 24], [29, 63]], [[3, 21], [29, 63]], [[4, 22], [30, 63]],
  [[5, 22], [30, 63]], [[8, 20], [30, 63]], [[12, 19], [29, 63]],
  [[16, 24], [28, 44], [46, 63]], [[17, 25], [28, 44], [54, 62]],
  [[17, 26], [29, 43], [52, 60]], [[18, 26], [30, 42], [53, 60]],
  [[18, 26], [30, 41], [54, 59]], [[19, 26], [31, 40]],
  [[19, 25], [32, 39], [52, 59]], [[19, 25], [33, 38], [51, 60]],
  [[20, 25], [34, 37], [51, 60]], [[20, 24], [34, 37], [52, 59], [62, 63]],
  [[20, 24], [53, 58], [62, 63]], [[21, 24], [54, 57], [62, 63]],
  [[21, 23]], [[21, 23]], [[21, 22]], [[21, 22]], [], [], [],
  [[0, 63]], [[0, 63]],
];

// Country pins as {col, row} on the 64x32 grid (nudged to reduce overlap).
const COUNTRY_COORDS = {
  "USA": [16, 9], "Canada": [13, 6], "England": [31, 6], "France": [32, 8],
  "Netherlands": [33, 6], "Denmark": [34, 5], "Sweden": [35, 4],
  "Japan": [57, 9], "Australia": [56, 20], "New Zealand": [62, 22],
};

function isLand(col, row) {
  const spans = LAND[row];
  if (!spans) return false;
  return spans.some(([s, e]) => col >= s && col <= e);
}

function drawWorldMap(canvas, px) {
  canvas.width = MAP_W * px;
  canvas.height = MAP_H * px;
  const ctx = canvas.getContext("2d");
  ctx.imageSmoothingEnabled = false;
  ctx.fillStyle = "#14233f";                 // ocean
  ctx.fillRect(0, 0, canvas.width, canvas.height);
  for (let row = 0; row < MAP_H; row++) {
    for (let col = 0; col < MAP_W; col++) {
      if (!isLand(col, row)) continue;
      let color = "#4f8a3f";                  // land
      if (row >= 30) color = "#c8d2dc";       // Antarctic ice
      else if (!isLand(col, row - 1)) color = "#63a24d";  // top-lit coastline
      ctx.fillStyle = color;
      ctx.fillRect(col * px, row * px, px, px);
    }
  }
}

function countByCountry() {
  const counts = {};
  APPLES.forEach((a) => { counts[a.origin.country] = (counts[a.origin.country] || 0) + 1; });
  return counts;
}

function renderMarkers() {
  const box = $("#markers");
  box.innerHTML = "";
  const counts = countByCountry();
  Object.entries(COUNTRY_COORDS).forEach(([country, [col, row]]) => {
    const n = counts[country] || 0;
    if (!n) return;
    const m = document.createElement("button");
    m.className = "marker";
    m.style.left = `${((col + 0.5) / MAP_W) * 100}%`;
    m.style.top = `${((row + 0.5) / MAP_H) * 100}%`;
    m.title = `${country} — ${n} ${n === 1 ? "apple" : "apples"}`;
    m.innerHTML = `<span class="marker-dot"></span><span class="marker-count">${n}</span>`;
    m.addEventListener("click", () => setCountry(country));
    box.appendChild(m);
  });
}

/* ---- State + data -------------------------------------------------------- */
const USES = ["eating", "baking", "cider", "sauce", "salad", "storage"];
let APPLES = [];
const state = { query: "", uses: new Set(), sort: "name", view: "grid", country: null };

const $ = (sel) => document.querySelector(sel);
const grid = $("#grid");

async function boot() {
  try {
    const res = await fetch("apples.json");
    const data = await res.json();
    APPLES = data.apples;
  } catch (err) {
    grid.innerHTML = `<p class="empty">Couldn't load apples.json.<br>Run <code>python serve.py</code> and open via http://localhost:8000</p>`;
    return;
  }
  buildUseFilters();
  wireControls();
  drawWorldMap($("#worldmap"), 10);
  renderMarkers();
  render();
}

function buildUseFilters() {
  const box = $("#use-filters");
  USES.forEach((use) => {
    const chip = document.createElement("button");
    chip.className = "chip";
    chip.textContent = use;
    chip.addEventListener("click", () => {
      chip.classList.toggle("active");
      if (state.uses.has(use)) state.uses.delete(use);
      else state.uses.add(use);
      render();
    });
    box.appendChild(chip);
  });
}

function wireControls() {
  $("#search").addEventListener("input", (e) => { state.query = e.target.value.toLowerCase().trim(); render(); });
  $("#sort").addEventListener("change", (e) => { state.sort = e.target.value; render(); });
  $("#modal-close").addEventListener("click", closeModal);
  $("#modal").addEventListener("click", (e) => { if (e.target.id === "modal") closeModal(); });
  document.addEventListener("keydown", (e) => { if (e.key === "Escape") closeModal(); });

  $("#tab-grid").addEventListener("click", () => showView("grid"));
  $("#tab-map").addEventListener("click", () => showView("map"));

  $("#random").addEventListener("click", () => {
    // Pick from whatever is currently visible, so filters still apply.
    const pool = APPLES.filter(matches);
    const list = pool.length ? pool : APPLES;
    openModal(list[Math.floor(Math.random() * list.length)]);
  });

  const toggle = $("#theme-toggle");
  const syncGlyph = () =>
    (toggle.textContent = document.documentElement.getAttribute("data-theme") === "light" ? "☀" : "☾");
  syncGlyph();
  toggle.addEventListener("click", () => {
    const next = document.documentElement.getAttribute("data-theme") === "light" ? "dark" : "light";
    document.documentElement.setAttribute("data-theme", next);
    localStorage.setItem("orchard-theme", next);
    syncGlyph();
  });
}

/* ---- Filtering + sorting ------------------------------------------------- */
function matches(a) {
  if (state.country && a.origin.country !== state.country) return false;
  for (const u of state.uses) if (!a.best_for.includes(u)) return false;   // AND across chips
  if (!state.query) return true;
  const hay = [
    a.name, a.aka.join(" "), a.origin.country, a.origin.region,
    a.parentage, a.notes, a.flavor_text, a.season,
  ].join(" ").toLowerCase();
  return hay.includes(state.query);
}

function sortApples(list) {
  const s = state.sort;
  const by = {
    name: (a, b) => a.name.localeCompare(b.name),
    sweetness: (a, b) => b.sweetness - a.sweetness || a.name.localeCompare(b.name),
    tartness: (a, b) => b.tartness - a.tartness || a.name.localeCompare(b.name),
    crispness: (a, b) => b.crispness - a.crispness || a.name.localeCompare(b.name),
    year: (a, b) => a.origin.year - b.origin.year || a.name.localeCompare(b.name),
  };
  return [...list].sort(by[s] || by.name);
}

/* ---- View + country filter ----------------------------------------------- */
function showView(view) {
  state.view = view;
  $("#grid").classList.toggle("hidden", view !== "grid");
  $("#map-view").classList.toggle("hidden", view !== "map");
  $("#tab-grid").classList.toggle("active", view === "grid");
  $("#tab-map").classList.toggle("active", view === "map");
}

function setCountry(country) {
  state.country = country;
  showView("grid");
  render();
  window.scrollTo({ top: 0, behavior: "smooth" });
}

function clearCountry() {
  state.country = null;
  render();
}

function renderActiveCountry() {
  const box = $("#active-country");
  box.innerHTML = "";
  if (!state.country) return;
  const chip = document.createElement("button");
  chip.className = "country-chip";
  const fe = flagEl(state.country);
  if (fe) chip.appendChild(fe);
  chip.appendChild(document.createTextNode(` FROM ${state.country.toUpperCase()} ✕`));
  chip.title = "Clear country filter";
  chip.addEventListener("click", clearCountry);
  box.appendChild(chip);
}

/* ---- Rendering ----------------------------------------------------------- */
function render() {
  const list = sortApples(APPLES.filter(matches));
  $("#count").textContent = `${list.length} / ${APPLES.length} CULTIVARS`;
  renderActiveCountry();
  grid.innerHTML = "";
  if (!list.length) {
    grid.innerHTML = `<p class="empty">No apples match that. Try fewer filters. 🍂</p>`;
    return;
  }
  list.forEach((a) => grid.appendChild(card(a)));
}

function card(a) {
  const el = document.createElement("div");
  el.className = "card";
  el.tabIndex = 0;

  const canvas = document.createElement("canvas");
  canvas.className = "sprite";
  el.appendChild(canvas);

  const name = document.createElement("div");
  name.className = "card-name";
  name.textContent = a.name;
  el.appendChild(name);

  const origin = document.createElement("div");
  origin.className = "card-origin";
  const fe = flagEl(a.origin.country);
  if (fe) origin.appendChild(fe);
  origin.appendChild(document.createTextNode(` ${a.origin.country} · ${a.origin.year}`));
  el.appendChild(origin);

  const tags = document.createElement("div");
  tags.className = "card-tags";
  a.best_for.slice(0, 3).forEach((u) => {
    const t = document.createElement("span");
    t.className = "tag";
    t.textContent = u;
    tags.appendChild(t);
  });
  el.appendChild(tags);

  el.addEventListener("click", () => openModal(a));
  el.addEventListener("keydown", (e) => { if (e.key === "Enter") openModal(a); });

  drawSprite(canvas, a.skin, 7, a.blush);
  return el;
}

function meter(label, value, cls) {
  const row = document.createElement("div");
  row.className = "meter";
  const lab = document.createElement("span");
  lab.className = "meter-label";
  lab.textContent = label;
  row.appendChild(lab);
  const pips = document.createElement("div");
  pips.className = "pips";
  for (let i = 1; i <= 5; i++) {
    const p = document.createElement("span");
    p.className = "pip" + (i <= value ? ` on-${cls}` : "");
    pips.appendChild(p);
  }
  row.appendChild(pips);
  return row;
}

/* ---- Modal --------------------------------------------------------------- */
function openModal(a) {
  const body = $("#modal-body");
  body.innerHTML = "";

  const head = document.createElement("div");
  head.className = "modal-head";
  const canvas = document.createElement("canvas");
  head.appendChild(canvas);
  const htext = document.createElement("div");
  htext.innerHTML =
    `<h2 id="modal-name" class="modal-name">${a.name}</h2>` +
    (a.aka.length ? `<div class="modal-aka">aka ${a.aka.join(", ")}</div>` : "");
  head.appendChild(htext);
  body.appendChild(head);

  const flavor = document.createElement("div");
  flavor.className = "flavor";
  flavor.textContent = `“${a.flavor_text}”`;
  body.appendChild(flavor);

  const stats = document.createElement("div");
  stats.className = "stats-block";
  stats.appendChild(meter("SWEET", a.sweetness, "sweet"));
  stats.appendChild(meter("TART", a.tartness, "tart"));
  stats.appendChild(meter("CRISP", a.crispness, "crisp"));
  body.appendChild(stats);

  const originRow = document.createElement("div");
  originRow.className = "field-row";
  originRow.innerHTML = `<span class="field-key">ORIGIN</span>`;
  const originVal = document.createElement("span");
  originVal.className = "field-val";
  const mfe = flagEl(a.origin.country);
  if (mfe) originVal.append(mfe, document.createTextNode(" "));
  originVal.append(document.createTextNode(`${a.origin.region}, ${a.origin.country} — ${a.origin.year}`));
  originRow.appendChild(originVal);
  body.appendChild(originRow);

  body.appendChild(field("PARENTAGE", a.parentage));

  const seasonRow = document.createElement("div");
  seasonRow.className = "field-row";
  seasonRow.innerHTML = `<span class="field-key">SEASON</span>`;
  const sb = document.createElement("span");
  sb.className = "badge season";
  sb.textContent = a.season;
  seasonRow.appendChild(sb);
  body.appendChild(seasonRow);

  const useRow = document.createElement("div");
  useRow.className = "field-row";
  useRow.innerHTML = `<span class="field-key">BEST FOR</span>`;
  const badges = document.createElement("div");
  badges.className = "badges";
  a.best_for.forEach((u) => {
    const b = document.createElement("span");
    b.className = "badge use";
    b.textContent = u;
    badges.appendChild(b);
  });
  useRow.appendChild(badges);
  body.appendChild(useRow);

  const notes = document.createElement("div");
  notes.className = "notes";
  notes.textContent = a.notes;
  body.appendChild(notes);

  drawSprite(canvas, a.skin, 8, a.blush);
  $("#modal").classList.remove("hidden");
}

function field(key, val) {
  const row = document.createElement("div");
  row.className = "field-row";
  row.innerHTML = `<span class="field-key">${key}</span><span class="field-val">${val}</span>`;
  return row;
}

function closeModal() { $("#modal").classList.add("hidden"); }

boot();
